config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get 'administration/index'

  get 'administration/show'
  # get 'administration/show', to: 'administration#index'
  # post 'administration/show'


  get 'main/index'

  get 'main/show'
  # get 'main/show', to: 'main#index'
  # post 'main/show'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  include CourtBook

  def index
  end

  def show
  end

  private

  def set_court_names
    court_names = [
      "日比谷公園",\
      "芝公園",\
      "猿江恩賜公園",\
      "亀戸中央公園",\
      "木場公園",\
      "祖師谷公園"\
      "東白鬚公園",\
      "浮間公園",\
      "城北中央公園Ａ",\
      "城北中央公園Ｂ",\
      "赤塚公園",\
      "東綾瀬公園",\
      "舎人公園",\
      "篠崎公園Ａ",\
      "大島小松川公園Ａ",\
      "汐入公園",\
      "善福寺川緑地",\
      "光が丘公園",\
      "石神井公園Ｂ",\
      "井の頭恩賜公園",\
      "武蔵野中央公園",\
      "小金井公園",\
      "野川公園",\
      "府中の森公園",\
      "東大和南公園",\
      "大井ふ頭海浜公園Ａ（ハード）",\
      "大井ふ頭海浜公園Ａ（人工芝）",\
      "大井ふ頭海浜公園B（ハード）",\
      "有明テニスの森公園Ａ（ハード）",\
      "有明テニスの森公園Ｂ（ハード）",\
      "有明テニスの森公園Ｃ／テニス（人工芝）"
    ]
    return court_names
  end

  def set_rsrv_times
    rsrv_times = [
      "9:00",\
      "11:00",\
      "13:00",\
      "15:00",\
      "17:00",\
      "19:00"
    ]
    return rsrv_times
  end
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/index.html.erb
<div class="col-xs-12">
  <h1>IMGPicker</h1>
  <p>post your request URL</p>
</div>

<div class="col-xs-12 form-group">
  <%= form_tag(main_index_path, method: :post) do %>
    <div>
      <p>URL : </p>
      <input type="url" name="imgpick-url" required>
    </div>
    <div>
      <p>DEPTH : </p>
      <input type="number" name="imgpick-depth" required>
    </div>
    <div>
      <p>SIZE : </p>
      height : <input type="number" name="imgpick-height" required>
      width : <input type="number" name="imgpick-width" required>
    </div>
    <div>
      <input type="submit" value="PICK UP">
    </div>
  <% end %>
</div>

app/views/main/show.html.erb
<h1>Main#show</h1>
<p>Find me in app/views/main/show.html.erb</p>