config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  get 'administration/index'

  get 'administration/show'
  # get 'administration/show', to: 'administration#index'
  # post 'administration/show'


  get 'main/index'

  get 'main/show'
  # get 'main/show', to: 'main#index'
  # post 'main/show'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/administration_controller.rb
class AdministrationController < ApplicationController
  def index
  end

  def show
    url = params[:imgpick_url]
    depth = params[:imgpick_depth].to_i
    height = params[:imgpick_height].to_i
    width = params[:imgpick_width].to_i
    @host = Utility::Scrap.get_host(url)
    @fqdn = Utility::Scrap.get_fqdn(url)
    @pick_imgs = []
    # pick_img_refs = pick_img_ref_nokogiri(url, depth, height, width)
    begin
      pick_img_refs = Utility::Scrap.get_img(url, depth)
    rescue => e
      error_msg = "Unknown error occured! Check logs!"
      Utility::ErrorHandling.output_task_log(e,error_msg)
      return []
    end
    pick_img_refs.each do |pick_img_ref|
      begin
        pick_img = Utility::Imageprocess.get_image(pick_img_ref, height, width)
      rescue => e
        error_msg = "Unknown error occured! Check logs!"
        Utility::ErrorHandling.output_task_log(e,error_msg)
        break
      end
      if pick_img.present?
        @pick_imgs.push({ref: pick_img_ref, columns: pick_img.columns, rows: pick_img.rows})
      else
        next
      end
    end
  end
end

app/helpers/administration_helper.rb
module AdministrationHelper
end

app/views/administration/index.html.erb
<div class="col-xs-12">
  <a class="h1" href="/administration/index">Administration#index</a>
  <p>Find me in app/views/administration/index.html.erb</p>
</div>

<div class="col-xs-12">
  <h1>IMGPicker</h1>
  <p>post your request URL</p>
</div>

<div class="col-xs-12 form-group">
  <%= form_tag(administration_show_path, method: :get) do %>
    <div>
      <p>URL : </p>
      <input type="url" name="imgpick_url" required>
    </div>
    <div>
      <p>DEPTH : </p>
      <input type="number" name="imgpick_depth"
    </div>
    <div>
      <p>SIZE : </p>
      height : <input type="number" name="imgpick_height">
      width : <input type="number" name="imgpick_width">
    </div>
    <div>
      <input type="submit" value="PICK UP">
    </div>
  <% end %>
</div>

app/views/administration/show.html.erb
<div class="col-xs-12">
  <a class="h1" href="/administration/index">Administration#show</a>
  <p>Find me in app/views/administration/show.html.erb</p>
</div>

<div class="col-xs-12">
  <h3><%= @rm_image %></h3>
  <h1>IMGPicker</h1>
  <h3><%= @host %></h3>
  <p>your request imgs here!</p>
</div>

<% @pick_imgs.each do |pick_img| %>
  <div class="col-xs-3 grid-img">
    <div>
      <a href="<%= pick_img[:ref] %>">
        <img class="img-responsive img-thumbnail center-block" src="<%= pick_img[:ref] %>" alt="img"/>
      </a>
    </div>
    <div>
      <p>columns: <%= pick_img[:columns] %></p>
      <p>rows: <%= pick_img[:rows] %></p>
    </div>
  </div>
<% end %>